INSERT INTO evenement (titel, organisatie) VALUES ('Buurtfeest Kuregem', 'Samen voor Anderlecht');
INSERT INTO evenement (titel, organisatie) VALUES ('Voetbaltoernooi Jeugd', 'RSCA Social');
INSERT INTO evenement (titel, organisatie) VALUES ('Soep in de Wijk', 'NGO Anderlecht');
INSERT INTO evenement (titel, organisatie) VALUES ('Zomeravond aan het Kanaal','Kanaal Anderlecht');
INSERT INTO evenement (titel, organisatie) VALUES ('Lichtjesmarkt op het Dapperheidsplein','Handelaarsvereniging Dapperheidsplein');
INSERT INTO evenement (titel, organisatie) VALUES ('Natuurweekend','Natuurpunt Anderlecht');
INSERT INTO evenement (titel, organisatie) VALUES ('Muziek onder de Toren','Sint-Guidofeesten VZW');
INSERT INTO evenement (titel, organisatie) VALUES ('Winterfeest Kuregem','Buurtwerking Kuregem Connect');
INSERT INTO evenement (titel, organisatie) VALUES ('URBAN ART & STREET Culture Festival','Anderlecht Creatief Collectief');
INSERT INTO evenement (titel, organisatie) VALUES ('Anderlecht Danst!','Cultuurplatform Sint-Guido');